stages:
  - test
  - sonar
  - deploy

UnitTest:
  image: python:3.6
  stage: test
  before_script:
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
    - echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list
    - pip install -r requirements.txt
    - python manage.py makemigrations
    - python manage.py migrate
    - python manage.py runserver 8000 &
  when: on_success
  script:
    - coverage run --include='hello/*,crossroads/*,enhancer/*' --omit='*/tests.py' manage.py test && coverage report -m && coverage xml

  artifacts:
    paths:
      - coverage.xml

pylint:
  image: python:3.6
  stage: test
  before_script:
    - pip install -r requirements.txt
    - pip install pylint pylint-exit
  script:
    - mkdir ./pylint
    - pylint --output-format=text crossroads/tests.py crossroads/views.py crossroads/validator.py enhancer/compressor.py enhancer/image_processor.py enhancer/tests.py | tee ./pylint/pylint.txt || pylint-exit $?
  artifacts:
    paths:
      - ./pylint/pylint.txt

SonarScanner:
  image: addianto/sonar-scanner-cli:latest
  stage: sonar
  script:
    - sonar-scanner
      -Dsonar.host.url=https://pmpl.cs.ui.ac.id/sonarqube
      -Dsonar.login=$SONARQUBE_TOKEN
      -Dsonar.branch.name=$CI_COMMIT_REF_NAME

DeploymentStaging:
  image: ruby:2.4
  stage: deploy
  variables:
    URL_FE: $FE_STAGING
    URL_BE: $HEROKU_APP_HOST
  before_script:
    - gem install dpl
    - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
    - heroku config:set DISABLE_COLLECTSTATIC=1 --app $HEROKU_APPNAME --api-key=$HEROKU_APIKEY
  script:
    - dpl --provider=heroku --app=$HEROKU_APPNAME --api-key=$HEROKU_APIKEY
    - export HEROKU_API_KEY=$HEROKU_APIKEY
    - heroku run --app $HEROKU_APPNAME migrate
  environment:
    name: staging
    url: $HEROKU_APP_HOST
  only:
    - staging

DeploymentProduction:
  image: ruby:2.4
  stage: deploy
  variables:
    URL_FE: $FE_PROD
    URL_BE: $HEROKU_APP_HOST_PROD
  before_script:
    - gem install dpl
    - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
    - heroku config:set DISABLE_COLLECTSTATIC=1 --app $HEROKU_APPNAME_PROD --api-key=$HEROKU_APIKEY
  script:
    - dpl --provider=heroku --app=$HEROKU_APPNAME_PROD --api-key=$HEROKU_APIKEY
    - export HEROKU_API_KEY=$HEROKU_APIKEY
    - heroku run --app $HEROKU_APPNAME_PROD migrate
  environment:
    name: production
    url: $HEROKU_APP_HOST_PROD
  only:
    - master
  when: manual