---
version: '3'
services:
  web:
    build: .
    stdin_open: true
    tty: true
    command: gunicorn smartcrm_backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    expose:
      - 8000
    env_file:
      - ./.env.staging

  nginx:
    build: ./nginx
    stdin_open: true
    tty: true
    ports:
      - 1337:80
    depends_on:
      - web
